name: Build and publish
on:
  push:
    tags:
      - v*
jobs:
  deploy-app:
    name: Deploy app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wasm
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/setup-node@v2-beta

      - name: Get Tag
        run: |
          echo "PUBLISH_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "Publishing tag ${{ env.PUBLISH_TAG }}"

      - name: Check Tools
        run: |
          rustc --version
          cargo --version

      - name: Install dependencies
        run: yarn install

      - name: Compile and bundle application
        run: yarn build

      - name: Deploy to github pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true
